name: "Destroy PR environment"

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      branch-prefix:
        description: 'Prefix of branch to be destroyed'
        required: true

jobs:
  derive_environment_prefix:
    name: "Derive environment prefix"
    runs-on: ubuntu-latest
    steps:
      # Use the first 7 chars of the hash of the branch name or passed in value, if triggered manually
      - name: "Derive environment prefix"
        id: derive-prefix
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request_target" ]; then
            echo ::set-output name=branch-prefix::$(echo ${{ github.head_ref }} | md5sum | awk '{print tolower(substr( $0, 1, 7))}')
          else
            echo ::set-output name=branch-prefix::$(echo ${{ github.event.inputs.branch-prefix }})
          fi

      - name: "Print environment prefix"
        shell: bash
        run: echo "Branch prefix ${{ steps.derive-prefix.outputs.branch-prefix }} will be used to destroy resources"

    outputs:
      prefix: ${{ steps.derive-prefix.outputs.branch-prefix }}

  get_rg_outputs:
    name: "Get resource group outputs"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/resource_group
    env:
      ARM_CLIENT_ID: ${{ secrets.NON_PROD_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.NON_PROD_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 93b71b78-b75b-4806-8282-97b9e70ae16c
      ARM_TENANT_ID: ${{ secrets.NON_PROD_ARM_TENANT_ID }}
      TF_INPUT: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
          terraform_wrapper: false

      - name: "Terraform Init"
        run: |
          terraform init \
            -lock-timeout=15m \
            -backend-config="./backends/dev.backend"

      - name: "Set Terraform Outputs"
        id: set-terraform-outputs
        run: |
          terraform output -json > rg-outputs.json
          echo ::set-output name=resource-group-name::$( jq -r .resource_group_name.value rg-outputs.json)

    outputs:
      resource_group_name: ${{ steps.set-terraform-outputs.outputs.resource-group-name }}

  get_apim_outputs:
    name: "Get APIM outputs"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/apim
    env:
      ARM_CLIENT_ID: ${{ secrets.NON_PROD_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.NON_PROD_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 93b71b78-b75b-4806-8282-97b9e70ae16c
      ARM_TENANT_ID: ${{ secrets.NON_PROD_ARM_TENANT_ID }}
      TF_INPUT: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
          terraform_wrapper: false

      - name: "Terraform Init"
        run: |
          terraform init \
            -lock-timeout=15m \
            -backend-config="./backends/dev.backend"

      - name: "Set Terraform Outputs"
        id: set-terraform-outputs
        run: |
          terraform output -json > apim-outputs.json
          echo ::set-output name=apim-name::$( jq -r .apim_name.value apim-outputs.json )
          echo ::set-output name=apim-vnet-name::$( jq -r .apim_vnet_name.value apim-outputs.json )
          echo ::set-output name=apim-subnet-name::$( jq -r .apim_subnet_name.value apim-outputs.json )
          echo ::set-output name=cdn-profile-website-name::$( jq -r .cdn_profile_website_name.value apim-outputs.json )
          echo ::set-output name=cdn-profile-storybook-name::$( jq -r .cdn_profile_storybook_name.value apim-outputs.json )
          echo ::set-output name=app-insights-name::$( jq -r .app_insights_name.value apim-outputs.json )
          echo ::set-output name=version-set-id::$( jq -r .version_set_id.value apim-outputs.json )

    outputs:
      apim_name: ${{ steps.set-terraform-outputs.outputs.apim-name }}
      apim_vnet_name: ${{ steps.set-terraform-outputs.outputs.apim-vnet-name }}
      apim_subnet_name: ${{ steps.set-terraform-outputs.outputs.apim-subnet-name }}
      cdn_profile_website_name: ${{ steps.set-terraform-outputs.outputs.cdn-profile-website-name }}
      cdn_profile_storybook_name: ${{ steps.set-terraform-outputs.outputs.cdn-profile-storybook-name }}
      app_insights_name: ${{ steps.set-terraform-outputs.outputs.app-insights-name }}
      version_set_id: ${{ steps.set-terraform-outputs.outputs.version-set-id }}

  destroy_pr_frontend_infra:
    name: "Clean up PR frontend"
    runs-on: ubuntu-latest
    needs:
      - derive_environment_prefix
      - get_rg_outputs
      - get_apim_outputs
    defaults:
      run:
        working-directory: ./terraform/frontend
    env:
      ARM_CLIENT_ID: ${{ secrets.NON_PROD_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.NON_PROD_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 93b71b78-b75b-4806-8282-97b9e70ae16c
      ARM_TENANT_ID: ${{ secrets.NON_PROD_ARM_TENANT_ID }}
      TF_INPUT: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: "Terraform Init"
        run: |
          terraform init \
            -lock-timeout=15m \
            -backend-config="./backends/pr.backend" \
            -backend-config="key=${{ needs.derive_environment_prefix.outputs.prefix }}/terraform.tfstate"

      - name: "Terraform Destroy"
        run: |
          terraform destroy \
            -lock-timeout=15m \
            -auto-approve \
            -var-file="./var-files/dev.tfvars"
        env:
          TF_VAR_environment_prefix: ${{ needs.derive_environment_prefix.outputs.prefix }}
          TF_VAR_resource_group_name: ${{ needs.get_rg_outputs.outputs.resource_group_name }}
          TF_VAR_apim_name: ${{ needs.get_apim_outputs.outputs.apim_name }}
          TF_VAR_cdn_profile_website_name: ${{ needs.get_apim_outputs.outputs.cdn_profile_website_name }}
          TF_VAR_cdn_profile_storybook_name: ${{ needs.get_apim_outputs.outputs.cdn_profile_storybook_name }}
          TF_VAR_app_insights_name: ${{ needs.get_apim_outputs.outputs.app_insights_name }}
          TF_VAR_git_branch_name: ${{ github.head_ref }}

  destroy_pr_backend_infra:
    name: "Clean up PR backend"
    runs-on: ubuntu-latest
    needs:
      - derive_environment_prefix
      - get_rg_outputs
      - get_apim_outputs
    defaults:
      run:
        working-directory: ./terraform/backend
    env:
      ARM_CLIENT_ID: ${{ secrets.NON_PROD_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.NON_PROD_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 93b71b78-b75b-4806-8282-97b9e70ae16c
      ARM_TENANT_ID: ${{ secrets.NON_PROD_ARM_TENANT_ID }}
      TF_INPUT: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: "Terraform Init"
        run: |
          terraform init \
            -lock-timeout=15m \
            -backend-config="./backends/pr.backend" \
            -backend-config="key=${{ needs.derive_environment_prefix.outputs.prefix }}/backend.tfstate"

      - name: "Terraform Destroy"
        run: |
          terraform destroy \
            -lock-timeout=15m \
            -auto-approve \
            -var-file="./var-files/dev.tfvars"
        env:
          TF_VAR_apim_name: ${{ needs.get_apim_outputs.outputs.apim_name }}
          TF_VAR_apim_vnet_name: ${{ needs.get_apim_outputs.outputs.apim_vnet_name }}
          TF_VAR_apim_subnet_name: ${{ needs.get_apim_outputs.outputs.apim_subnet_name }}
          TF_VAR_app_insights_name: ${{ needs.get_apim_outputs.outputs.app_insights_name }}
          TF_VAR_cdn_profile_website_name: ${{ needs.get_apim_outputs.outputs.cdn_profile_website_name }}
          TF_VAR_cdn_profile_storybook_name: ${{ needs.get_apim_outputs.outputs.cdn_profile_storybook_name }}
          TF_VAR_environment_prefix: ${{ needs.derive_environment_prefix.outputs.prefix }}
          TF_VAR_frontend_cdn_url: stukstsw${{ needs.derive_environment_prefix.outputs.prefix }}dh.azureedge.net
          TF_VAR_git_branch_name: ${{ github.head_ref }}
          TF_VAR_resource_group_name: ${{ needs.get_rg_outputs.outputs.resource_group_name }}
          TF_VAR_version_set_id: ${{ needs.get_apim_outputs.outputs.version_set_id }}
          TF_VAR_myaccounts_aes_key: ${{ secrets.MYACCOUNTS_AES_KEY }}
          TF_VAR_myaccounts_aes_key_vector: ${{ secrets.MYACCOUNTS_AES_KEY_VECTOR }}

  destroy_launchdarkly_env:
    name: "Clean up LaunchDarkly environment"
    runs-on: ubuntu-latest
    needs:
      - derive_environment_prefix
    defaults:
      run:
        working-directory: ./terraform/launch_darkly
    env:
      ARM_CLIENT_ID: ${{ secrets.NON_PROD_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.NON_PROD_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 93b71b78-b75b-4806-8282-97b9e70ae16c
      ARM_TENANT_ID: ${{ secrets.NON_PROD_ARM_TENANT_ID }}
      LAUNCHDARKLY_ACCESS_TOKEN: ${{ secrets.LAUNCHDARKLY_API_KEY }}
      TF_INPUT: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: "Terraform Init"
        run: |
          terraform init \
            -lock-timeout=15m \
            -backend-config="./backends/pr.backend" \
            -backend-config="key=${{ needs.derive_environment_prefix.outputs.prefix }}/launchdarkly.tfstate"

      - name: "Terraform Destroy"
        run: |
          terraform destroy \
            -lock-timeout=15m \
            -auto-approve \
            -var-file="./var-files/pr.tfvars"
        env:
          TF_VAR_environment_name: ${{ needs.derive_environment_prefix.outputs.prefix }}
