name: Shell Command

on:
  schedule:
    - cron: '5 * * * *'
  #push:
  #pull_request:
  #types: [closed,assigned,opened,reopened]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
        - name: echo a string
          run: |
            echo "Hello World"
            echo $GITHUB_REPOSITORY
            echo "Hello Mars"
            echo "Hello Jupiter"
            echo "Hello Old Jupiter"
        - name: multiplescript
          run: |
           node -v
           npm -v
  
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

          
