name: Shell Command

on:
  #schedule:
  # - cron: '0/10 * * * *'
  push:
  pull_request:
   types: [closed,assigned,opened,reopened]
jobs:
  #first Job
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: this is a workflow job
    steps:
        - name: echo a string
          run: |
            echo "Hello World"
            echo "The Job Description is '${JOB_VARIABLE}'"
            echo "The Code Repository is '${GITHUB_REPOSITORY}'""
            echo "Hello Mars"
            echo "Hello Jupiter"
            echo "Hello Old Jupiter"
        - name: multiplescript
          run: |
           node -v
           npm -v
  
  run-windows-command:
    #second Job
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

          
