name: Shell Command

on: [push]

jobs:
  #first Job
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
        - name: echo a string
          run: echo "Hello World"
        - name: multiplescript
          run: |
           node -v
           npm -v
  
  run-windows-command:
    #second Job
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

          
