name: Shell Command

on:
  #schedule:
  # - cron: '0/10 * * * *'
  push:
    branches:
      - "main"
  pull_request:
   types: [closed,assigned,opened,reopened]
env:
  WF_VARIABLE: this is a sample workflow
  OWNER_NAME: ${{secrets.OWNER_NAME}}
jobs:
  #first Job
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: this is a workflow job
    steps:
        - name: echo a string
          env:
            STEP_VARIABLE: this is a step in the job
          run: |
            echo "Hello World"
            echo "The Workflow Description is '${WF_VARIABLE}'"
            echo "The Job Description is '${JOB_VARIABLE}'"
            echo "The Step Description is '${STEP_VARIABLE}'"
            echo "The Code Repository is '${GITHUB_REPOSITORY}'"
            echo "The Owner Name is '${OWNER_NAME}'"
            echo "Hello Mars"
            echo "Hello Jupiter"
            echo "Hello Old Jupiter"
        - name: multiplescript
          run: |
           node -v
           npm -v
  
  run-windows-command:
    #second Job
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

          
